---
# yamllint disable rule:key-ordering rule:line-length
name: build-audit
on: # yamllint disable-line
  pull_request:
    branches:
    - main
    types:
    - assigned
    - opened
    - synchronize
    - reopened
jobs:
  build-unminified-site:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Build site with Hugo and audit
      uses: wildtechgarden/audit-build-action-hugo@main
      with:
        base-url: "https://example.com/"
        config-file: hugo.toml
        hugo-version: latest
        upload-site-as: unminified-site
        source-directory: tests/config
    - name: Validate HTML in output-directory
      uses: ./
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        use-existing-workspace: "true"
  validate-html-artifact:
    needs: build-unminified-site
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Validate HTML from artifact
      uses: ./
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
...
